server:
  port: 8081
  
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate_search?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: alpar
    password: qwertyui  
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        search:
          enabled: true
          schema_management:
            strategy: drop-and-create
          backend:
            hosts: localhost:9200         
         